# To run locally:
#   make docker-test

name: Test
on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false

      - name: test & coverage report creation
        run: make test-all-with-coverage

      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
