name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  golangci:
    # We need to run the linter on the same image we use for building, since it
    # needs the C libraries installed for the dependencies to typecheck.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Set up Docker Build
          uses: docker/setup-buildx-action@v3.0.0
          with:
            driver: docker
  
        - name: Build Docker image
          uses: docker/build-push-action@v5
          with:
            context: ./tools
            file: ./tools/Dockerfile
            tags: "cometbft/cometbft-db-testing:latest"
            load: true


        - name: Run golangci-lint
          run: make docker-lint


